import assert from 'node:assert/strict';
import { createArenaClassesClient } from '../src/modules/arenaClasses/model/client.js';

const now = Date.parse('2026-09-22T12:00:00Z');
const dataset = { classes: [{ id: 'mage', name: 'Маг', winrate: 51.2, color: '#2b5c85' }], updatedAt: new Date(now).toISOString(), source: 'hsreplay' };
const entries = new Map<string, string>();
const storage = { getItem: (key: string) => entries.get(key) ?? null, setItem: (key: string, value: string) => { entries.set(key, value); }, removeItem: (key: string) => { entries.delete(key); } };
let clock = now;
let response = () => Promise.resolve(Response.json(dataset, { headers: { ETag: '"one"' } }));
const client = createArenaClassesClient({ storage, now: () => clock, request: () => response() });
const load = (account = 'user-1') => client.load(account, 'hsreplay');

response = () => Promise.resolve(new Response(null, { status: 503 }));
assert.deepEqual(await load(), { status: 'error', data: null });
response = () => Promise.resolve(Response.json({ ...dataset, classes: [] }));
assert.equal((await load()).status, 'empty');
response = () => Promise.resolve(Response.json(dataset, { headers: { ETag: '"one"' } }));
assert.equal((await load()).status, 'ready');
response = () => Promise.reject(new Error('offline'));
assert.equal((await load()).status, 'stale');
assert.equal((await load()).data?.classes[0].winrate, 51.2);
assert.deepEqual(await load('different-user'), { status: 'error', data: null });
response = () => Promise.resolve(new Response(null, { status: 304, headers: { 'X-Data-Cache': 'memory-stale' } }));
assert.equal((await load()).status, 'stale');
response = () => Promise.resolve(new Response(null, { status: 403 }));
assert.deepEqual(await load(), { status: 'error', data: null });
assert.equal(entries.size, 0, 'authorization failures clear protected cached data');
let calls = 0;
response = () => Promise.resolve(++calls === 1 ? new Response(null, { status: 304 }) : Response.json(dataset));
assert.equal((await load()).status, 'ready');
assert.equal(calls, 2, 'a 304 without a usable cache retries unconditionally');
clock += 6 * 60 * 60_000 + 1;
response = () => Promise.reject(new Error('offline'));
assert.deepEqual(await load(), { status: 'error', data: null });
response = () => Promise.resolve(Response.json({ ...dataset, source: 'initial' }));
assert.equal((await load()).status, 'error', 'synthetic initial data cannot become real cache');
response = () => Promise.resolve(Response.json({ ...dataset, classes: [{ ...dataset.classes[0], winrate: 150 }] }));
assert.equal((await load()).status, 'error');
response = () => Promise.resolve(Response.json(dataset));
assert.equal((await load()).status, 'stale', 'old server snapshots remain visibly stale');
console.log('Arena classes data-state and account cache tests passed');
