// Deterministic API data for browser QA. Browser request interception
// (scripts/e2e-qa.mjs) and the QA backend read by Next.js server rendering
// (scripts/qa/backend.mjs) answer from these same values, so server HTML and
// hydrated client state describe one fixture world.
export const qaCardImage = 'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" width="400" height="560" viewBox="0 0 400 560"%3E%3Crect width="400" height="560" rx="34" fill="%233b254b"/%3E%3Crect x="22" y="22" width="356" height="516" rx="26" fill="%23c49a55"/%3E%3Crect x="42" y="42" width="316" height="300" rx="18" fill="%236d1117"/%3E%3Ccircle cx="200" cy="188" r="92" fill="%23f0cf77"/%3E%3Cpath d="M145 235L200 105l55 130z" fill="%235b3470"/%3E%3Crect x="58" y="366" width="284" height="126" rx="18" fill="%23f7e8bf"/%3E%3Ctext x="200" y="420" text-anchor="middle" font-size="25" font-family="serif" font-weight="700" fill="%233d2a1e"%3EQA CARD%3C/text%3E%3Ctext x="200" y="458" text-anchor="middle" font-size="17" font-family="sans-serif" fill="%235c4938"%3EManacost%3C/text%3E%3C/svg%3E';
const qaCardGoldenImage = `${qaCardImage}#golden`;
const qaCard = {
  cardId: 'TIME_890',
  name: 'Медив Освященный',
  imageHa: qaCardGoldenImage,
  imageRu: qaCardImage,
};
const qaArticleCover = 'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" width="1176" height="597" viewBox="0 0 1176 597"%3E%3Crect width="1176" height="597" fill="%236d1117"/%3E%3C/svg%3E';
const qaArticles = [
  { id: 'qa-article-1', title: 'Первая статья', date: '2026-07-11', tag: 'Арена', excerpt: 'Контрольная статья Арены.', mode: 'arena', image: qaArticleCover, url: '/articles/qa-1' },
  { id: 'qa-article-2', title: 'Вторая статья', date: '2026-07-10', tag: 'Общее', excerpt: 'Контрольный общий материал.', mode: 'general', image: qaArticleCover, url: '/articles/qa-2' },
];
export const qaDeckCards = Array.from({ length: 17 }, (_, index) => ({
  id: `CARD_QA_${index + 1}`,
  dbfId: 1000 + index,
  name: `Контрольная карта ${index + 1}`,
  cost: index,
  rarity: index === 0 ? 'LEGENDARY' : index % 3 === 0 ? 'EPIC' : 'COMMON',
  elite: index === 0,
  count: index === 0 ? 1 : 2,
  image: index % 2 ? qaCard.imageRu : qaCard.imageHa,
  cardImage: qaCard.imageRu,
}));
const qaClasses = [
  ['paladin', 'Паладин', '#a88a45', 54.6],
  ['hunter', 'Охотник', '#1d5921', 52.6],
  ['mage', 'Маг', '#2b5c85', 51.8],
  ['priest', 'Жрец', '#d1d1d1', 50.9],
  ['death-knight', 'Рыцарь смерти', '#1f252d', 49.8],
  ['demon-hunter', 'Охотник на демонов', '#224722', 48.7],
  ['rogue', 'Разбойник', '#333333', 47.6],
  ['shaman', 'Шаман', '#2a2e6b', 46.5],
  ['warlock', 'Чернокнижник', '#5c265c', 45.4],
  ['druid', 'Друид', '#704a16', 44.3],
  ['warrior', 'Воин', '#7a1e1e', 43.2],
].map(([id, name, color, winrate], index) => ({ id, name, color, winrate, games: 1500 - index * 50 }));
export const qaArchetypeItems = [
  ['qa-evenlock', 'Evenlock', 'Чётный Чернокнижник', 'warlock', 6476, 61.1, 5.9, 14],
  ['qa-painlock', 'Painlock', 'Пейнлок', 'warlock', 536, 60.4, 0.5, 7],
  ['qa-handbuff-warrior', 'Handbuff Warrior', 'Воин на усилениях', 'warrior', 136, 58.1, 0.1, 5],
  ['qa-mug-shaman', 'Mug Shaman', 'Кружечный Шаман', 'shaman', 3736, 56.8, 3.4, 9],
  ['qa-face-hunter', 'Face Hunter', 'Фейс Охотник', 'hunter', 2980, 55.3, 2.7, 8],
].map(([slug, archetype, archetypeLabel, classKey, games, winrate, popularity, deckCount]) => ({
  slug,
  archetype,
  archetypeLabel,
  translated: true,
  classKey,
  format: 'standard',
  games,
  winrate,
  popularity,
  turns: 6.2,
  durationMinutes: 5.3,
  climbingSpeed: 2.49,
  deckCount,
  builds: [],
  sourceUrl: `https://www.hsguru.com/archetype/${archetype}`,
}));
const qaArchetypeBuilds = Array.from({ length: 14 }, (_, index) => ({
  deckCode: `AAECAf0GQaFixtureArchetypeDeckCode${index + 1}ForBrowserQualityAssurance==`,
  games: 1200 - index * 45,
  winrate: 61.1 - index * 0.3,
  sourceUrl: `https://www.hsguru.com/deck/${index + 1}`,
  updatedAt: '2026-07-24T00:00:00.000Z',
  classKey: 'warlock',
  sampleRank: 'all',
  samplePeriod: 'past_30_days',
}));
export const qaArchetypeCatalog = {
  format: 'standard',
  formatLabel: 'Стандарт',
  patch: '36.0.3',
  minimumGames: 50,
  updatedAt: '2026-07-24T00:00:00.000Z',
  coverage: { archetypes: qaArchetypeItems.length, builds: 43 },
  items: qaArchetypeItems,
};
export const qaArchetypeDetail = {
  format: 'standard',
  formatLabel: 'Стандарт',
  patch: '36.0.3',
  minimumGames: 50,
  updatedAt: '2026-07-24T00:00:00.000Z',
  item: { ...qaArchetypeItems[0], builds: qaArchetypeBuilds },
  history: Array.from({ length: 4 }, (_, index) => ({
    recordedAt: `2026-07-${String(21 + index).padStart(2, '0')}T00:00:00.000Z`,
    games: 5900 + index * 192,
    winrate: 59.9 + index * 0.4,
    popularity: 5.3 + index * 0.2,
    turns: 6.2,
    durationMinutes: 5.3,
    climbingSpeed: 2.49,
  })),
};
export const fixtures = {
  '/api/home/summary': {
    topClasses: qaClasses.slice(0, 3),
    topCards: [{ ...qaCard, score: 100, rarity: 'legendary', tier: 'S', classKey: 'any', cost: 10 }],
    topLegendaries: [{ ...qaCard, winRate: 59.5, classKey: 'priest', cost: 10 }],
    battlegroundSpotlight: null,
    updatedAt: {
      winrates: '2026-07-11T00:00:00.000Z',
      tierlist: '2026-07-11T00:00:00.000Z',
      legendaries: '2026-07-11T00:00:00.000Z',
      battlegrounds: '2026-07-11T00:00:00.000Z',
    },
    sources: { winrates: 'qa-fixture', tierlist: 'qa-fixture', legendaries: 'qa-fixture' },
  },
  '/api/winrates': {
    classes: qaClasses,
    updatedAt: '2026-07-11T00:00:00.000Z',
    source: 'qa-fixture',
  },
  '/api/tierlist': {
    sections: [{
      id: 'any',
      name: 'Нейтральные',
      color: '#4a4a4a',
      tiers: [{
        tier: 'S',
        label: 'Отлично',
        description: 'Контрольный тир.',
        cards: [{ ...qaCard, score: 100, winrate: 59.5, rarity: 'legendary', classKey: 'any' }],
      }],
    }, ...qaClasses.map(cls => ({ ...cls, tiers: [], totalCards: 0 }))],
    cards: {
      TIME_890: { cost: 10, attack: 7, health: 7, type: 'minion', rarity: 'legendary', imageHa: qaCard.imageHa, imageRu: qaCard.imageRu },
    },
    updatedAt: '2026-07-11T00:00:00.000Z',
    source: 'hsreplay.net',
  },
  '/api/legendaries': {
    groups: [
      { keyCard: qaCard, cards: [], winRate: 66.3, classKey: 'priest' },
      { keyCard: { ...qaCard, cardId: 'TIME_890_BLUE', name: 'Медив Освященный II' }, cards: [], winRate: 55.2, classKey: 'mage' },
      { keyCard: { ...qaCard, cardId: 'TIME_890_RED', name: 'Медив Освященный III' }, cards: [], winRate: 42.1, classKey: 'warrior' },
    ],
    updatedAt: '2026-07-11T00:00:00.000Z',
    source: 'hsreplay.net',
  },
  '/api/bg/tier-lists': {
    list: 'spells',
    source: 'qa-fixture',
    fetchedAt: '2026-07-11T00:00:00.000Z',
    count: 0,
    tierCounts: {},
    tiers: {},
  },
  '/api/bg/heroes': {
    ok: true,
    source_id: 'qa-heroes',
    fetched_at: '2026-07-11T00:00:00.000Z',
    view: {
      heroes: [{
        tier: 'S', hero: 'Контрольный герой', dbfId: 9001,
        avg_placement: 3.72, pick_rate: '12,4%', placement_distribution: ['18%', '16%', '14%', '13%', '12%', '10%', '9%', '8%'],
        image: qaCard.imageRu,
        hero_power: { card: { dbf: 9002, name: 'Контрольная сила героя', text: 'Даёт преимущество.', image: qaCard.imageRu } },
      }, {
        tier: 'S', hero: 'Повелитель кошмаров Ксавий', dbfId: 132608,
        avg_placement: 3.58, pick_rate: '88,64%', image: qaCard.imageRu,
      }, {
        tier: 'C', hero: "Трас'тат, паразит душ", dbfId: 132578,
        avg_placement: 4.37, pick_rate: '74,02%', image: qaCard.imageRu,
      }, ...Array.from({ length: 90 }, (_, index) => ({
        tier: ['A', 'B', 'C', 'D'][index % 4],
        hero: `Контрольный герой пула ${index + 1}`,
        dbfId: 9100 + index,
        avg_placement: 3.8 + (index % 10) / 10,
        pick_rate: '10,00%',
        image: qaCard.imageRu,
      }))],
    },
  },
  '/api/bg/heroes/9001/details': {
    ok: true,
    fetched_at: '2026-07-11T00:00:00.000Z',
    stats: {
      hero: {
        hero: 'Контрольный герой', dbfId: 9001, tier: 'S', avg_placement: 3.72, pick_rate: '12,4%',
        best_composition: 'Звери', placement_distribution: ['18%', '16%', '14%', '13%', '12%', '10%', '9%', '8%'],
      },
      as_of: { hero: '2026-07-11T00:00:00.000Z' },
      compositions: [{ name: 'Звери', avg_placement: 3.4, popularity: '11%', num_games: 120 }],
      best_composition: { name: 'Звери', final_form_minions: [] },
      hero_power: [{ turn: 3, tavern_tier: 2, gold: 6, invoked_rate: 61, times_invoked: 90, total_data_points: 120 }],
      hero_power_by_turn: [{ turn: 3, invoked_rate: 61, total_data_points: 120 }, { turn: 4, invoked_rate: 72, total_data_points: 110 }],
      tavern_up_by_turn: [{ turn: 3, recommended_tavern_tier: 2, pct_at_tier: 64 }],
      tavern_up: [{ turn: 3, tavern_tier: 2, pct_at_tier: 64 }],
      source_url: 'https://hsreplay.net/battlegrounds/heroes/',
    },
    libraryHero: {
      name: { ru: 'Контрольный герой', en: 'QA Hero' },
      images: { hero: qaCard.imageRu, full_art: qaCard.imageRu },
      hero_power: { card: { dbf: 9002, name: 'Контрольная сила героя', text: { ru: 'Даёт преимущество.' }, image: qaCard.imageRu } },
      armor: { normal: 10, duos: 8 },
      updated_at: '2026-07-11T00:00:00.000Z',
    },
    cards: {},
  },
  '/api/bg/library/extra/heroes': {
    data: [{
      card_id: 'BG_HERO_QA_9001',
      dbf: 9001,
      name: { ru: 'Контрольный герой', en: 'QA Hero' },
      images: { hero: qaCard.imageRu, full_art: qaCard.imageRu },
      hero_power: {
        card: {
          dbf: 9002,
          name: 'Контрольная сила героя',
          text: 'Даёт преимущество.',
          image: qaCard.imageRu,
        },
      },
      armor: { normal: 10, duos: 8 },
      updated_at: '2026-07-11T00:00:00.000Z',
    }, {
      card_id: 'BG36_HERO_105',
      dbf: 132608,
      name: { ru: 'Повелитель кошмаров Ксавий', en: 'Nightmare Lord Xavius' },
      images: { hero: qaCard.imageRu, full_art: qaCard.imageRu },
      updated_at: '2026-08-04T00:00:00.000Z',
    }, {
      card_id: 'BG36_HERO_101',
      dbf: 132578,
      name: { ru: "Трас'тат, паразит душ", en: "Tras'tath, Soul Parasite" },
      images: { hero: qaCard.imageRu, full_art: qaCard.imageRu },
      updated_at: '2026-08-04T00:00:00.000Z',
    }],
    pagination: { page: 1, perPage: 200, total: 3, totalPages: 1 },
  },
  '/api/bg/library/meta': {
    creature_types: [{ slug: 'beast', name_ru: 'Зверь' }],
    mechanics: [{ slug: 'battlecry', name_ru: 'Боевой клич' }],
  },
  '/api/bg/library/cards': {
    data: [{
      card_id: 'BG_QA_1', dbf: 9101, card_type: { slug: 'minion', name_ru: 'Существо' },
      name: { ru: 'Контрольное существо', en: 'QA Minion' }, tavern_tier: 3,
      creature_type: { slug: 'beast', name_ru: 'Зверь' }, attack: 4, health: 5, in_pool: true,
      mechanics: [{ slug: 'battlecry', name_ru: 'Боевой клич' }], text: { ru: 'Боевой клич: получите преимущество.' },
      images: { card: qaCard.imageRu, golden: qaCard.imageRu, art: qaCard.imageRu },
      source: 'qa-fixture', updated_at: '2026-07-11T00:00:00.000Z',
    }],
  },
  '/api/bg/library/cards/by-dbf/9101': {
    card_id: 'BG_QA_1', dbf: 9101, card_type: { slug: 'minion', name_ru: 'Существо' },
    name: { ru: 'Контрольное существо', en: 'QA Minion' }, tavern_tier: 3,
    creature_type: { slug: 'beast', name_ru: 'Зверь' }, attack: 4, health: 5, in_pool: true,
    mechanics: [{ slug: 'battlecry', name_ru: 'Боевой клич' }], text: { ru: 'Боевой клич: получите преимущество.' },
    images: { card: qaCard.imageRu, golden: qaCard.imageRu, art: qaCard.imageRu },
    source: 'qa-fixture', updated_at: '2026-07-11T00:00:00.000Z',
  },
  '/api/bg/library/minions/9101': {
    dbf_id: 9101, card_id: 'BG_QA_1', name: 'QA Minion', name_ru: 'Контрольное существо', tavern_tier: 3,
    impact: 0.42, combat_winrate: 55.1, popularity: 12.4, games_with_minion: 200, games_without_minion: 800,
    avg_placement_with: 3.7, avg_placement_without: 4.2,
    rounds: [
      { combat_round: 8, games_with_minion: 90, games_without_minion: 300, avg_placement_with: 3.9, avg_placement_without: 4.3, impact: 0.4, combat_winrate: 54, wins: 49, losses: 41 },
      { combat_round: 9, games_with_minion: 110, games_without_minion: 500, avg_placement_with: 3.6, avg_placement_without: 4.1, impact: 0.5, combat_winrate: 56, wins: 62, losses: 48 },
    ],
  },
  '/api/standard/matchups': {
    format: 'standard', formatLabel: 'Стандарт',
    rank: 'legend', rankLabel: 'Легенда', source: 'hsguru', updatedAt: '2026-07-11T00:00:00.000Z',
    columns: [
      { name: 'Control Warrior', label: 'Контроль Воин', popularity: '12,4%' },
      { name: 'Rainbow Mage', label: 'Радужный Маг', popularity: '9,8%' },
    ],
    rows: [
      { archetype: 'Control Warrior', archetypeLabel: 'Контроль Воин', winrate: 52.4, cells: [{ opponent: 'Control Warrior', opponentLabel: 'Контроль Воин', winrate: 50 }, { opponent: 'Rainbow Mage', opponentLabel: 'Радужный Маг', winrate: 54.8 }] },
      { archetype: 'Rainbow Mage', archetypeLabel: 'Радужный Маг', winrate: 49.6, cells: [{ opponent: 'Control Warrior', opponentLabel: 'Контроль Воин', winrate: 45.2 }, { opponent: 'Rainbow Mage', opponentLabel: 'Радужный Маг', winrate: 50 }] },
    ],
  },
  '/api/guides-archive': {
    page: 1,
    limit: 18,
    total: 1,
    totalPages: 1,
    items: [{
      id: 1,
      slug: 'qa-guide',
      title: 'Контрольный гайд Арены',
      description: 'Детерминированная запись для проверки адаптивного архива.',
      image: null,
      publishedAt: '2026-07-11T00:00:00.000Z',
      menuName: 'Арена',
      menuCode: 'arena',
      kind: 'Гайд',
      kindSlug: 'guide',
      oldUrl: 'https://old.kolodahearthstone.ru/qa-guide',
    }],
    filters: {
      kinds: [{ slug: 'guide', label: 'Гайд', count: 1 }],
      menus: [{ slug: 'arena', label: 'Арена', count: 1 }],
    },
  },
  '/api/articles': {
    articles: qaArticles,
  },
  '/api/search': {
    query: 'контроль',
    minimumQueryLength: 2,
    articles: [{
      id: 'qa-search-article', title: 'Контрольный мета-отчет', excerpt: 'Проверка поиска.', tag: 'Мета-отчет',
      mode: 'standard', date: '2026-07-18', url: 'https://kolodahearthstone.com/qa-vip/', image: qaArticleCover, vip: true,
    }],
    cards: [{
      id: 'CARD_QA_1', name: 'Контрольная карта', nameEn: 'QA Card', text: 'Боевой клич.', image: qaCard.imageRu,
      mana: 1, className: 'MAGE', cardType: 'Существо', formats: ['standard', 'wild'], path: '/standard/cards/standard/CARD_QA_1',
    }],
  },
  // Anonymous projections read only by Next.js server rendering, in the shapes
  // the Express public routes return for the same fixture entities.
  '/api/public/constructed-cards/standard/CARD_QA_1': {
    card: {
      id: 'CARD_QA_1', name: 'Контрольная карта 1', englishName: 'QA Card 1',
      rulesText: 'Боевой клич: возьмите карту.', flavorText: 'Контрольный художественный текст.',
      set: 'Побег из Аметистовой крепости', type: 'Заклинание', className: 'Воин', rarity: 'Легендарная',
      mana: 1, attack: null, health: null, durability: null, armor: null, artist: 'QA Artist',
      image: 'https://hearthpulse.net/api/card-image/CARD_QA_1/full.webp',
    },
    classCode: 'WARRIOR',
    dbf: 9000,
  },
  '/api/constructed-archetypes/teaser/standard/qa-evenlock': {
    format: 'standard',
    formatLabel: 'Стандарт',
    patch: '36.0.3',
    minimumGames: 50,
    updatedAt: '2026-07-24T00:00:00.000Z',
    item: qaArchetypeItems[0],
    featuredBuild: {
      games: 1200, winrate: 61.1, updatedAt: '2026-07-24T00:00:00.000Z', sampleRank: 'all', samplePeriod: 'past_30_days',
    },
  },
  '/api/bg/heroes/public/9001': {
    hero: {
      dbfId: 9001, cardId: 'BG_HERO_QA_9001', name: 'Контрольный герой',
      image: 'https://hearthpulse.net/api/card-image/BG_HERO_QA_9001/full.webp',
      heroPower: {
        name: 'Контрольная сила героя', text: 'Даёт преимущество.',
        image: 'https://hearthpulse.net/api/card-image/BG_HERO_QA_9002/full.webp',
      },
    },
  },
  '/api/bg/library/public/minion/9101': {
    card: {
      dbfId: 9101, kind: 'minion', typeName: 'Существо', nameRu: 'Контрольное существо', nameEn: 'QA Minion',
      textRu: 'Боевой клич: получите преимущество.', textEn: null, tavernTier: 3, tribe: 'Зверь',
      attack: 4, health: 5, mechanics: ['Боевой клич'],
      images: { card: '/api/card-image/BG_QA_1/full.webp', golden: null, art: null, framed: null, crop: null },
      artist: null, inPool: true,
    },
    canonicalPath: '/library/minions/контрольное-существо-9101/',
  },
};
export const subscriber = {
  hasAccess: true,
  source: 'qa-fixture',
  checkedAt: new Date().toISOString(),
  stale: false,
  message: 'Deterministic browser QA subscriber',
  entitlements: {
    arena: true,
    battlegrounds: true,
    standard: true,
    contests: true,
    guidesArchive: true,
    arenaArticles: true,
    battlegroundsArticles: true,
  },
  boosty: { checked: true, found: true, hasAccess: true },
  telegram: { checked: false, hasAccess: false },
};
export const adminFixtures = {
  '/api/articles': { articles: qaArticles },
  '/api/admin/constructed-cards': {
    format: 'standard', rank: 'legend', timeRange: '1d', updatedAt: '2026-07-16T05:03:02.000Z', sourceUrl: 'https://hsreplay.net/cards/',
    // Collection metadata the Express catalog always returns; the Next.js
    // server loader rejects a catalog without it.
    period: { id: '1d', label: 'Последний день', timeRange: 'LAST_1_DAY', patch: null },
    dataStatus: 'fresh', cacheSource: 'fresh', partial: false, datasetVersion: 'qa-fixture',
    statsAccess: true,
    mechanicTranslations: { BATTLECRY: 'Боевой клич', TAUNT: 'Провокация' },
    cards: Array.from({ length: 8 }, (_, index) => ({
      card_id: `CARD_QA_${index + 1}`, dbf: 9000 + index, name: { ru: `Контрольная карта ${index + 1}`, en: `QA Card ${index + 1}` },
      card_set: index % 2 ? 'CATACLYSM' : 'ESCAPEFROM_VIOLET_HOLD', card_type: { slug: index % 2 ? 'MINION' : 'SPELL', name_ru: index % 2 ? 'Существо' : 'Заклинание' },
      class: index % 2 ? 'MAGE' : 'WARRIOR', multi_class: [], rarity: index % 3 ? 'RARE' : 'LEGENDARY',
      mana_cost: index + 1, attack: index % 2 ? index + 1 : null, health: index % 2 ? index + 2 : null,
      mechanics: index % 2 ? ['BATTLECRY'] : [], referenced_tags: index % 2 ? ['TAUNT'] : [],
      images: { card: qaCard.imageRu, crop: qaCard.imageRu },
      stats: index === 7 ? null : {
        deckPopularity: 18.4 - index, deckWinrate: 56.2 - index * 0.4, averageCopies: 1.7, timesPlayed: 12400 - index * 800,
        winrateWhenPlayed: 55.8, winrateWhenDrawn: 54.6, keepPercentage: 42.1, openingHandWinrate: 53.2,
        averageTurnsInHand: 2.1, averageTurnPlayed: 4.4,
      },
    })),
    facets: { classes: ['MAGE', 'WARRIOR'], sets: ['CATACLYSM', 'ESCAPEFROM_VIOLET_HOLD'], mechanics: ['BATTLECRY', 'TAUNT'], types: ['MINION', 'SPELL'], rarities: ['LEGENDARY', 'RARE'] },
    facetCounts: {
      classes: [{ value: 'MAGE', count: 4 }, { value: 'WARRIOR', count: 4 }],
      sets: [{ value: 'CATACLYSM', count: 4 }, { value: 'ESCAPEFROM_VIOLET_HOLD', count: 4 }],
      mechanics: [{ value: 'BATTLECRY', count: 4 }, { value: 'TAUNT', count: 4 }],
      types: [{ value: 'MINION', count: 4 }, { value: 'SPELL', count: 4 }],
      rarities: [{ value: 'LEGENDARY', count: 3 }, { value: 'RARE', count: 5 }],
    },
    coverage: { totalCards: 1152, cardsWithStats: 1013, cardsWithoutStats: 139, totalSets: 7 },
    pagination: { page: 1, perPage: 60, total: 8, totalPages: 1 },
  },
  '/api/admin/constructed-cards/CARD_QA_1': {
    format: 'standard', rank: 'legend', statsAccess: true, mechanicTranslations: { BATTLECRY: 'Боевой клич', TAUNT: 'Провокация' },
    card: {
      card_id: 'CARD_QA_1', dbf: 9000, name: { ru: 'Контрольная карта 1', en: 'QA Card 1' },
      text: { ru: '<b>Боевой клич:</b> возьмите карту.' }, flavor: { ru: 'Контрольный художественный текст.' },
      card_set: 'ESCAPEFROM_VIOLET_HOLD', card_type: { slug: 'SPELL', name_ru: 'Заклинание' }, class: 'WARRIOR', multi_class: [], rarity: 'LEGENDARY',
      mana_cost: 1, attack: null, health: null, artist: 'QA Artist', mechanics: ['BATTLECRY', 'Battlecry'], referenced_tags: ['TAUNT'],
      images: { card: qaCard.imageRu, golden: null, signature: null, diamond: null, crop: '/arena-logo-icon.webp?v=arena-legacy-20260629' },
      statsUpdatedAt: '2026-07-16T05:03:02.000Z', statsSourceUrl: 'https://hsreplay.net/cards/',
      stats: { deckPopularity: 18.4, deckWinrate: 56.2, averageCopies: 1.7, timesPlayed: 12400, winrateWhenPlayed: 55.8, winrateWhenDrawn: 54.6, keepPercentage: 42.1, openingHandWinrate: 53.2, averageTurnsInHand: 2.1, averageTurnPlayed: 4.4 },
      wiki_page: { title: 'QA Card 1', url: 'https://example.test/wiki' },
      wiki: {
        golden_cards: [{ label: 'Golden', file_url: qaCard.imageHa }],
        wiki_mechanics: ['Battlecry', 'Draw cards'], wiki_tags: ['Hand-related'],
        patch_changes: [{ heading: 'Card changes', entries: [
          { date: '2025-02-01', patch: 'Patch 35.0', items: ['Changed.'], manacost_title: 'Обновление 35.0: контрольный патч', manacost_url: 'https://hs-manacost.ru/qa-patch-35/', manacost_published_at: '2025-02-01T12:00:00', manacost_summary: 'Русское описание контрольного обновления.' },
          { date: '2024-01-10', patch: 'Patch 34.0', items: ['Added.'], manacost_title: 'Обновление 34.0: ранний патч', manacost_url: 'https://hs-manacost.ru/qa-patch-34/', manacost_published_at: '2024-01-10T12:00:00', manacost_summary: 'Более раннее русское описание.' },
        ] }],
        related_cards: [{}, { card_id: 'CARD_QA_2', name_ru: 'Контрольная карта 2', image_url: qaCard.imageRu }],
        generated_card_pools: [{
          pool: 'Fire spells',
          card_ids: ['CARD_QA_2', 'CARD_QA_TOKEN'],
          cards: Array.from({ length: 12 }, (_, index) => index === 0
            ? { card_id: 'CARD_QA_2', name: { ru: 'Контрольная карта 2', en: 'QA Card 2' }, image_url: qaCard.imageRu, can_open: true }
            : { card_id: `CARD_QA_TOKEN_${index}`, name: { ru: `Контрольный токен ${index}`, en: `QA Token ${index}` }, image_url: qaCard.imageHa, url: `https://example.test/token-${index}`, can_open: false }),
        }],
        gallery: [{ caption: 'QA full art', file_url: '/wallpaper/arena-parchment.jpg', thumb_url: '/wallpaper/arena-parchment.jpg' }],
        sounds: [],
        external_links: [{ label: 'HSReplay.net', url: 'https://example.test/hsreplay' }],
      },
      related_cards_localized: [
        {
          heading: { ru: 'Варианты задания', en: 'Quest variants' },
          cards: [
            {
              card_id: 'CARD_QA_TOKEN_1', name: { ru: 'Первый этап', en: 'First Step' },
              text: { ru: 'Сыграйте контрольную карту.' }, mana_cost: 1, artist: 'QA Wiki Artist',
              images: {
                card: qaCard.imageRu, art: '/wallpaper/profile-hero-hth.jpg', crop: '/arena-logo-icon-256.webp',
                art_metadata: { file_page_url: 'https://example.test/wiki/file/shared', width: 3000, height: 4000, sha1: 'qa-shared-wiki-art' },
              },
              relationship: { wiki_url: 'https://example.test/wiki/token-1' },
            },
            {
              card_id: 'CARD_QA_TOKEN_2', name: { ru: 'Второй этап', en: 'Second Step' },
              text: { ru: 'Сыграйте ещё одну контрольную карту.' }, mana_cost: 2,
              images: {
                card: qaCard.imageHa, art: '/wallpaper/profile-hero-hth.jpg',
                art_metadata: { width: 3000, height: 4000, sha1: 'qa-shared-wiki-art' },
              },
              relationship: { wiki_url: 'https://example.test/wiki/token-2' },
            },
          ],
        },
        {
          heading: { ru: 'Награды', en: 'Rewards' },
          cards: [
            {
              card_id: 'CARD_QA_REWARD', name: { ru: 'Контрольная награда', en: 'QA Reward' },
              text: { ru: 'Получите контрольную награду.' }, mana_cost: 5, attack: 7, health: 7,
              images: {
                card: qaCard.imageRu, art: '/wallpaper/home-paladin-hero.webp',
                art_metadata: { file_page_url: 'https://example.test/wiki/file/reward', width: 3543, height: 4724, sha1: 'qa-reward-wiki-art' },
              },
              relationship: { wiki_url: 'https://example.test/wiki/reward' },
            },
            {
              card_id: 'CARD_QA_MISSING_ART', name: { ru: 'Карта без полного арта', en: 'Missing Full Art' },
              images: { card: qaCard.imageHa, crop: '/arena-logo-icon-256.webp' },
              relationship: { wiki_url: 'https://example.test/wiki/missing-art' },
            },
          ],
        },
      ],
      decks: Array.from({ length: 7 }, (_, index) => ({
        id: `qa-deck-${index + 1}`,
        title: `Контрольная колода ${index + 1}`,
        archetype: index % 2 ? 'Face Hunter' : 'Control Warrior',
        archetypeLabel: index % 2 ? 'Фейс Охотник' : 'Контроль Воин',
        className: index % 2 ? 'Hunter' : 'Warrior',
        deckCode: `AAECAQaFixtureDeckCode${index + 1}ForBrowserQualityAssurance1234567890==`,
        source: 'qa-fixture', sourceUrl: '', winrate: 55.4 - index, score: `${18 - index}-${8 + index}`,
        updatedAt: `2026-07-${String(16 - index).padStart(2, '0')}T12:00:00.000Z`,
      })),
    },
  },
  '/api/admin/standard-meta': {
    format: 'standard',
    formatLabel: 'Стандарт',
    rank: 'legend',
    rankLabel: 'Легенда',
    period: 'past_day',
    availablePeriods: ['past_day', 'past_3_days', 'past_week', 'past_2_weeks', 'patch_36.0.3', 'violet_hold'],
    currentPatchPeriod: 'patch_36.0.3',
    source: 'qa-fixture',
    sourceUrl: '',
    translationSource: 'qa-fixture',
    updatedAt: '2026-07-11T00:00:00.000Z',
    items: [
      {
        id: 'qa-evenlock', slug: 'qa-evenlock', archetype: 'Evenlock', archetypeLabel: 'Чётный Чернокнижник', translated: true,
        classKey: 'warlock', winrate: 61.1, popularity: 5.9, games: 6476, turns: 6.2,
        durationMinutes: 5.3, climbingSpeed: 2.49,
      },
      {
        id: 'qa-painlock', slug: 'qa-painlock', archetype: 'Painlock', archetypeLabel: 'Пейнлок', translated: true,
        classKey: 'warlock', winrate: 60.4, popularity: 0.5, games: 536, turns: 6.7,
        durationMinutes: 5.9, climbingSpeed: 2.11,
      },
      {
        id: 'qa-handbuff-warrior', slug: 'qa-handbuff-warrior', archetype: 'Handbuff Warrior', archetypeLabel: 'Воин на усилениях', translated: true,
        classKey: 'warrior', winrate: 58.1, popularity: 0.1, games: 136, turns: 4.6,
        durationMinutes: 3.7, climbingSpeed: 2.63,
      },
      {
        id: 'qa-mug-shaman', slug: 'qa-mug-shaman', archetype: 'Mug Shaman', archetypeLabel: 'Кружечный Шаман', translated: true,
        classKey: 'shaman', winrate: 56.8, popularity: 3.4, games: 3736, turns: 7.2,
        durationMinutes: 6.4, climbingSpeed: 1.2,
      },
      {
        id: 'qa-face-hunter', slug: 'qa-face-hunter', archetype: 'Face Hunter', archetypeLabel: 'Фейс Охотник', translated: true,
        classKey: 'hunter', winrate: 55.3, popularity: 2.7, games: 2980, turns: 6.8,
        durationMinutes: 6.1, climbingSpeed: 0.9,
      },
    ],
  },
  '/api/admin/vicious-syndicate-gold': {
    title: 'Vicious Syndicate Gold',
    format: 'Standard',
    games: 355561,
    source: 'Vicious Syndicate Live',
    sourceUrl: 'https://www.vicioussyndicate.com/',
    updatedAt: '2026-07-13T00:00:00.000Z',
    minimumDeckFrequency: 0.5,
    buildCoverage: { found: 2, total: 2 },
    classDistribution: [
      { class: 'warlock', classLabel: 'Чернокнижник', classIcon: 'warlock', frequency: 18.4 },
      { class: 'shaman', classLabel: 'Шаман', classIcon: 'shaman', frequency: 13.8 },
    ],
    deckDistribution: [{
      class: 'warlock', classLabel: 'Чернокнижник', classIcon: 'warlock', frequency: 7.36,
      deck: 'Painlock', deckLabel: 'Пейнлок',
      build: {
        deckCode: 'AAECAf0GQaFixtureViciousDeckCodeForBrowserQualityAssurance123456==',
        source: 'qa-fixture', sourceLabel: 'QA fixture', sourceUrl: '', matchedArchetype: 'Painlock',
        matchMethod: 'exact', updatedAt: '2026-07-13T00:00:00.000Z', winrate: 55.2, sampleGames: 900,
        deckCards: qaDeckCards,
      },
    }],
    tierList: [{
      rankBracket: 'All ranks', rankLabel: 'Все ранги',
      decks: [{
        rank: 1, class: 'warlock', classLabel: 'Чернокнижник', classIcon: 'warlock', winrate: 55.2,
        deck: 'Painlock', deckLabel: 'Пейнлок',
        build: {
          deckCode: 'AAECAf0GQaFixtureViciousDeckCodeForBrowserQualityAssurance123456==',
          source: 'qa-fixture', sourceLabel: 'QA fixture', sourceUrl: '', matchedArchetype: 'Painlock',
          matchMethod: 'exact', updatedAt: '2026-07-13T00:00:00.000Z', winrate: 55.2, sampleGames: 900,
          deckCards: qaDeckCards,
        },
      }],
    }],
  },
  '/api/admin/vicious-syndicate-gold/builds': {
    builds: [{
      deck: 'Painlock',
      build: {
        deckCode: 'AAECAf0GQaFixtureViciousDeckCodeForBrowserQualityAssurance123456==',
        source: 'qa-fixture', sourceLabel: 'QA fixture', sourceUrl: '', matchedArchetype: 'Painlock',
        matchMethod: 'exact', updatedAt: '2026-07-13T00:00:00.000Z', winrate: 55.2, sampleGames: 900,
        deckCards: qaDeckCards,
      },
    }],
    buildCoverage: { found: 1, total: 1 },
  },
  '/api/admin/contests': {
    contests: [{
      id: 'qa-contest',
      title: 'Контрольный конкурс',
      description: 'Детерминированный конкурс для browser QA.',
      prize: 'Приз',
      imageUrl: '',
      startsAt: '2026-07-11T00:00:00.000Z',
      endsAt: '2026-07-20T00:00:00.000Z',
      status: 'active',
      winners: [],
      entriesCount: 3,
    }],
  },
  '/api/admin/contests/qa-contest/entries': {
    entries: [
      {
        id: 'entry-qa-1', contestId: 'qa-contest', userId: 'user-qa-1', profileId: 'PROFILE-001', name: 'Одобренный участник',
        email: 'winner@example.test', status: 'approved', createdAt: '2026-07-11T01:00:00.000Z',
        contact: { telegram: '@winner' }, subscription: { hasAccess: true }, profileContacts: { vk: 'vk.com/winner', telegram: '@winner' },
      },
      {
        id: 'entry-qa-2', contestId: 'qa-contest', userId: 'user-qa-2', profileId: 'PROFILE-002', name: 'Участник на проверке',
        email: 'pending@example.test', status: 'pending', createdAt: '2026-07-11T02:00:00.000Z',
        contact: {}, subscription: { hasAccess: true }, profileContacts: {},
      },
    ],
  },
  '/api/admin/gallery': {
    items: [{
      id: 'qa-art',
      title: 'Контрольный арт',
      description: 'Детерминированный арт для browser QA.',
      tag: 'QA',
      source: 'fixture',
      width: 1920,
      height: 1080,
      bytes: 125000,
      previewUrl: '/favicon-192.png',
      thumbUrl: '/favicon-192.png',
      imageUrl: '/favicon-192.png',
      downloadUrl: '/favicon-192.png',
      createdAt: '2026-07-11T00:00:00.000Z',
    }],
  },
  '/api/admin/referrals': {
    referrals: [{
      id: 'qa-referral',
      slug: 'qa-campaign',
      label: 'QA campaign',
      campaign: 'qa',
      targetPath: '/',
      status: 'active',
      createdAt: '2026-07-11T00:00:00.000Z',
      updatedAt: '2026-07-11T00:00:00.000Z',
      url: 'https://hearthpulse.net/r/qa-campaign',
      clicks: 7,
      uniqueClicks: 5,
      lastClickAt: '2026-07-11T00:00:00.000Z',
    }],
    recentClicks: [],
  },
  '/api/admin/archetype-translations': {
    items: [
      {
        id: 1, blizzcoreId: 11, nameEn: 'Control Warrior', nameRu: 'Контроль Воин', source: 'blizzcore',
        createdAt: '2026-07-11T00:00:00.000Z', updatedAt: '2026-07-11T00:00:00.000Z',
        syncedAt: '2026-07-11T00:00:00.000Z', updatedBy: 'system',
      },
      {
        id: 2, blizzcoreId: null, nameEn: 'Rainbow Mage', nameRu: 'Радужный Маг', source: 'manual',
        createdAt: '2026-07-11T00:00:00.000Z', updatedAt: '2026-07-11T00:00:00.000Z',
        syncedAt: null, updatedBy: 'qa-admin',
      },
    ],
  },
  '/api/admin/mechanic-translations': {
    items: [
      { key: 'BATTLECRY', nameEn: 'Battlecry', nameRu: 'Боевой клич', source: 'default', kind: 'mechanic', cardCount: 412, updatedAt: null, example: { cardId: 'CARD_QA_2', name: { ru: 'Контрольная карта 2', en: 'QA Card 2' }, imageUrl: qaCard.imageRu, type: 'MINION' } },
      { key: 'NEW_MECHANIC', nameEn: 'New Mechanic', nameRu: '', source: 'missing', kind: 'tag', cardCount: 7, updatedAt: null, example: { cardId: 'CARD_QA_4', name: { ru: 'Контрольная карта 4', en: 'QA Card 4' }, imageUrl: qaCard.imageRu, type: 'MINION' } },
    ],
  },
  '/api/admin/standard-operations': {
    generatedAt: '2026-07-16T12:00:00.000Z',
    publicRoutes: ['/standard/cards'],
    diamondRoutes: ['/standard/matchups', '/standard/meta', '/standard/vicious-gold'],
    caches: { meta: { entries: 8, fresh: 8 }, viciousGold: { entries: 1, fresh: 1 }, recommendations: { entries: 24, active: 0 }, previews: { entries: 19, activeJobs: 0 } },
    deckView: { queued: 0, active: 0, succeeded: 31, failed: 1, timeoutMs: 30000 },
    sources: {
      viciousSyndicate: 'vicious-syndicate-live-standard',
      cardStatistics: {
        standard: { legend: { '1d': 'cards-standard-legend-1d', '3d': 'cards-standard-legend-3d' } },
        wild: { legend: { '1d': 'cards-wild-legend-1d' } },
      },
      renderApi: 'http://127.0.0.1:5000/deckview-api/v1',
    },
  },
  '/api/admin/parser-control': {
    revision: 3,
    generated_at: '2026-07-21T01:00:00.000Z',
    policy: {
      mode: 'stable', effective_mode: 'stable', early_until: null, reason: '',
      updated_at: '2026-07-21T00:30:00.000Z', updated_by: 'qa-admin', managed_by: 'admin',
    },
    sections: {
      standard: {
        group: 'traditional', label: 'Стандарт', description: 'Мета, матчапы и карты', enabled: true, status: 'healthy',
        last_success_at: '2026-07-21T00:00:00.000Z', schedule: 'каждые 5 часов',
        sources: [{
          source_id: 'vicious_syndicate_live', label: 'Vicious Syndicate Live', enabled: true,
          supports_early: true, can_run_manually: true, health: 'healthy',
          last_success_at: '2026-07-21T00:00:00.000Z', published_fetched_at: '2026-07-21T00:00:00.000Z',
          candidate_fetched_at: '2026-07-21T00:00:00.000Z', publication_channel: 'stable',
          stable_baseline_available: true, item_count: 128, state: 'ready',
        }],
      },
      arena: {
        group: 'arena', label: 'Арена', description: 'Тир-листы и винрейты', enabled: true, status: 'healthy',
        last_success_at: '2026-07-21T00:00:00.000Z', schedule: 'каждые 5 часов',
        sources: [{
          source_id: 'hsreplay_arena', label: 'HSReplay Arena', enabled: true,
          supports_early: true, can_run_manually: true, health: 'healthy',
          last_success_at: '2026-07-21T00:00:00.000Z', published_fetched_at: '2026-07-21T00:00:00.000Z',
          candidate_fetched_at: '2026-07-21T00:00:00.000Z', publication_channel: 'stable',
          stable_baseline_available: true, item_count: 731, state: 'ready',
        }],
      },
    },
    scheduleInventory: {
      schemaVersion: 2,
      inventoryVersion: '2026-07-21.2',
      generatedAt: '2026-07-21T01:00:00.000Z',
      timeSemantics: 'runtime',
      runtimeTimerStateIncluded: true,
      runtimeTimerState: {
        provider: 'host-systemd', checkedAt: '2026-07-21T01:00:00.000Z',
        available: true, status: 'ok', timingAvailable: true,
      },
      schedules: [{
        id: 'refresh-post-patch-tierlists',
        label: 'Каждые 5 часов с 21 по 27 июля 2026 года',
        systemdUnit: 'hs-data-api-docker-refresh-post-patch-tierlists.timer',
        onCalendar: [
          '2026-07-21 00,05,10,15,20:20:00 Europe/Warsaw',
          '2026-07-22 01,06,11,16,21:20:00 Europe/Warsaw',
        ],
        timezone: 'Europe/Warsaw',
        sourceIds: ['firestone_arena_cards_normal', 'heartharena_tierlist', 'hsreplay_arena_cards_advanced'],
        sectionIds: ['arena'],
        nominalNextRunAt: '2026-07-21T03:20:00+00:00',
        nextRunAt: '2026-07-21T03:21:00+00:00',
        nextRunAtSource: 'runtime',
        runtimeStateAvailable: true,
        enabled: true,
        active: true,
        lastRunAt: '2026-07-20T22:20:00+00:00',
        failure: null,
        loadState: 'loaded',
        activeState: 'active',
        subState: 'waiting',
        unitFileState: 'enabled',
        result: 'success',
        serviceUnit: 'hs-data-api-docker-refresh-post-patch-tierlists.service',
        serviceActiveState: 'inactive',
        serviceResult: 'success',
        validUntil: '2026-07-27T19:20:00+00:00',
        isActive: true,
      }],
    },
    summary: { total_sources: 2, enabled_sections: 2, early_capable_sources: 2, active_runs: 0, failed_sources: 0 },
    warnings: [],
  },
  '/api/admin/parser-control/runs': {
    runs: [{
      id: 'qa-run-1', status: 'partial', reason: 'Проверка после патча', requested_at: '2026-07-21T00:00:00.000Z',
      source_ids: ['hsreplay_arena'], requested_source_ids: ['hsreplay_arena', 'vicious_syndicate_live'],
      deduplicated_source_ids: ['vicious_syndicate_live'], total_sources: 1, completed_sources: 1, failed_sources: 1,
      results: [{
        source_id: 'hsreplay_arena', state: 'ok', serving_cached_dataset: true, rows_total: 731,
        error: 'Свежий ответ не прошёл проверку качества',
      }],
    }],
  },
  '/api/admin/parser-control/audit': {
    entries: [{
      id: 'qa-audit-1',
      actor: { id: 'qa-admin', name: 'QA администратор' },
      action: 'parser-control.policy.update',
      entityId: 'stable',
      details: {
        summary: 'Включена стабильная мета',
        revision: 3,
        requestId: 'qa-parser-audit-request',
        before: { revision: 2, mode: 'early' },
        after: { revision: 3, mode: 'stable' },
      },
      createdAt: '2026-07-21T01:00:00.000Z',
    }],
  },
  '/api/admin/boosty/status': {
    configured: true,
    ok: true,
    importStatus: 'ok',
    source: 'qa-fixture',
    stale: false,
    summary: { boostyPaid: 4, activePaid: 4 },
    checkedAt: '2026-07-11T00:00:00.000Z',
  },
  '/api/admin/boosty/subscribers': {
    configured: true,
    source: 'qa-fixture',
    stale: false,
    summary: { boostyPaid: 2, activePaid: 1 },
    levels: { 'Любитель Арены': 1, 'Зритель': 1 },
    subscribers: [
      {
        id: 'boosty-qa-1', name: 'Активный подписчик', email: 'active@example.test', hasEmail: true,
        avatarUrl: '', status: 'active', subscribed: true, active: true, paid: true, hasActivePaidAccess: true,
        willRenew: true, blacklisted: false, canWrite: true, audienceType: 'boosty-paid', contactStatus: 'known',
        level: { id: 1, name: 'Любитель Арены', price: 500, currency: 'RUB' },
        money: { currentPrice: 500, totalPayments: 1500, currency: 'RUB' },
        dates: { subscribedAt: '2026-06-01T00:00:00.000Z', unsubscribedAt: null, nextPaymentAt: '2026-08-01T00:00:00.000Z' },
        entitlements: { arena: true, battlegrounds: true }, siteAccess: true,
      },
      {
        id: 'boosty-qa-2', name: 'Неактивный подписчик', email: '', hasEmail: false,
        avatarUrl: '', status: 'inactive', subscribed: false, active: false, paid: false, hasActivePaidAccess: false,
        willRenew: false, blacklisted: false, canWrite: false, audienceType: 'boosty-free', contactStatus: 'missing-email',
        level: { id: 2, name: 'Зритель', price: 0, currency: 'RUB' },
        money: { currentPrice: 0, totalPayments: 0, currency: 'RUB' },
        dates: { subscribedAt: null, unsubscribedAt: '2026-06-02T00:00:00.000Z', nextPaymentAt: null },
        entitlements: {}, siteAccess: false,
      },
    ],
    fetchedAt: '2026-07-11T00:00:00.000Z',
  },
  '/api/admin/telegram/accounts': {
    configured: true,
    chatIds: ['-100123456'],
    summary: { total: 2, access: 1, checkable: 1, contactOnly: 1, stale: 1, blocked: 0 },
    accounts: [
      {
        id: 'telegram-qa-1', profileId: 'TG-0001', name: 'Участник VIP', email: 'vip@example.test', role: 'user', blockedAt: '',
        telegramId: '10001', telegramOidcId: 'oidc-10001', telegramUsername: 'vip_member', contactTelegram: 'vip_member', photoUrl: '',
        hasTelegramIdentity: true, hasContactOnly: false, canBeChecked: true, hasAccess: true, telegramHasAccess: true,
        accessState: 'access', source: 'telegram', message: 'Участник найден', checkedAt: '2026-07-11T00:00:00.000Z',
        updatedAt: '2026-07-11T00:00:00.000Z', stale: false, entitlements: { arena: true, battlegrounds: true },
        chats: [{ chatId: '-100123456', status: 'member', isMember: true, hasAccess: true }], boostyHasAccess: false,
        createdAt: '2026-07-01T00:00:00.000Z', userUpdatedAt: '2026-07-11T00:00:00.000Z',
      },
      {
        id: 'telegram-qa-2', profileId: 'TG-0002', name: 'Контакт без привязки', email: 'contact@example.test', role: 'user', blockedAt: '',
        telegramId: '', telegramOidcId: '', telegramUsername: 'contact_only', contactTelegram: 'contact_only', photoUrl: '',
        hasTelegramIdentity: false, hasContactOnly: true, canBeChecked: false, hasAccess: false, telegramHasAccess: false,
        accessState: 'contact-only', source: 'profile', message: 'Нужна привязка Telegram', checkedAt: '2026-05-01T00:00:00.000Z',
        updatedAt: '2026-07-11T00:00:00.000Z', stale: true, entitlements: {}, chats: [], boostyHasAccess: false,
        createdAt: '2026-07-02T00:00:00.000Z', userUpdatedAt: '2026-07-11T00:00:00.000Z',
      },
    ],
    fetchedAt: '2026-07-11T00:00:00.000Z',
  },
  '/api/admin/users': {
    users: [
      {
        id: 'qa-user-1',
        profileId: 'QA-0001',
        name: 'Первый пользователь',
        email: 'first@example.test',
        role: 'user',
        country: 'RU',
        telegramUsername: 'first_user',
        contactVkUrl: 'https://vk.com/hearthpulse_community_manager_with_a_long_contact_name',
        contactTelegram: '@hearthpulse_community_manager_with_a_long_contact_name',
        contactEmail: 'hearthpulse.community.manager.with.a.long.address@example.test',
        lifetimeAccess: false,
        manualAccess: { enabled: false, expiresAt: null },
        subscription: { hasAccess: true, source: 'qa', checkedAt: '2026-07-11T00:00:00.000Z' },
        contestEntriesCount: 2,
        createdAt: '2026-07-01T00:00:00.000Z',
      },
      {
        id: 'qa-user-2',
        profileId: 'QA-0002',
        name: 'Заблокированный пользователь',
        email: 'blocked@example.test',
        role: 'user',
        country: 'KZ',
        telegramUsername: '',
        contactVkUrl: '',
        contactTelegram: '',
        contactEmail: 'blocked@example.test',
        lifetimeAccess: false,
        manualAccess: { enabled: false, expiresAt: null },
        blockedAt: '2026-07-10T00:00:00.000Z',
        subscription: { hasAccess: false, source: 'qa', checkedAt: '2026-07-11T00:00:00.000Z' },
        contestEntriesCount: 0,
        createdAt: '2026-07-02T00:00:00.000Z',
      },
    ],
    total: 2,
  },
  '/api/admin/crm/segments': {
    segments: [
      { id: 'all', label: 'Все', count: 2 },
      { id: 'paying', label: 'Платят сейчас', count: 1 },
      { id: 'manual', label: 'Ручной доступ', count: 0 },
      { id: 'expiring', label: 'Истекает ≤ 7 дней', count: 0 },
      { id: 'lapsed', label: 'Потеряли доступ', count: 0 },
      { id: 'new', label: 'Новые за 7 дней', count: 0 },
      { id: 'blocked', label: 'Заблокированы', count: 1 },
      { id: 'admins', label: 'Администраторы', count: 0 },
    ],
    tags: [],
  },
  '/api/admin/crm/people/qa-user-1': {
    person: {
      id: 'qa-user-1', name: 'Первый пользователь', email: 'first@example.test', role: 'user', country: 'RU',
      createdAt: '2026-07-01T00:00:00.000Z', updatedAt: '2026-07-11T00:00:00.000Z', blockedAt: null, newsletterOptIn: true,
      contacts: { telegram: '@first_user', vk: '', email: '' },
    },
    identities: [{ provider: 'telegram', username: 'first_user', createdAt: '2026-07-01T00:00:00.000Z', verifiedAt: '2026-07-01T00:00:00.000Z' }],
    access: { hasAccess: true, source: 'boosty', message: 'Подписка Boosty активна.', checkedAt: '2026-07-11T00:00:00.000Z', manual: null },
    accessHistory: [{ at: '2026-07-02T00:00:00.000Z', source: 'boosty', hasAccess: true }],
    referral: { label: 'QA campaign', slug: 'qa', campaign: 'qa', clickedAt: '2026-06-30T23:50:00.000Z' },
    contests: [{ contestId: 'qa-contest', title: 'QA конкурс', status: 'approved', createdAt: '2026-07-05T00:00:00.000Z' }],
    mailing: { consentStatus: 'subscribed', consentedAt: '2026-07-01T00:00:00.000Z', unsubscribedAt: null, delivered: 1, failed: 0, lastDeliveredAt: '2026-07-10T00:00:00.000Z' },
    notes: [{ id: 1, body: 'QA заметка', authorId: 'qa-admin', authorName: 'QA администратор', createdAt: '2026-07-06T00:00:00.000Z' }],
    tags: ['vip'],
    audit: [],
  },
  '/api/admin/crm/overview': {
    generatedAt: '2026-07-28T00:00:00.000Z',
    alerts: [
      {
        id: 'telegram-chat:-5077378176',
        severity: 'critical',
        title: 'Бот не видит VIP-группу Telegram -5077378176',
        detail: '4 из 4 проверок за 2 часа: Bad Request: chat not found. Участники только этой группы не получают доступ.',
        action: { section: 'telegram', label: 'Открыть Telegram' },
      },
      {
        id: 'expiring-access',
        severity: 'warning',
        title: '1 ручной доступ истекает в ближайшие 7 дней',
        detail: 'Продлите доступ тем, кому он ещё нужен, пока он не закрылся.',
        action: { section: 'users', segment: 'expiring', label: 'Показать' },
      },
    ],
    kpis: { totalUsers: 2, payingNow: 1, payingProvider: 1, manualAccess: 0, newUsers30d: 2, newUsersPrevious30d: 1, lapsed30d: 0, expiringSoon: 1 },
    series: {
      days: Array.from({ length: 30 }, (_, index) => new Date(Date.UTC(2026, 5, 29 + index)).toISOString().slice(0, 10)),
      newUsers: Array.from({ length: 30 }, (_, index) => (index === 2 || index === 3 ? 1 : 0)),
      paying: Array.from({ length: 30 }, (_, index) => (index > 5 ? 1 : 0)),
    },
    activity: [
      { id: 'registration:qa-user-2', kind: 'registration', at: '2026-07-02T00:00:00.000Z', name: 'Заблокированный пользователь', userId: 'qa-user-2' },
      { id: 'registration:qa-user-1', kind: 'registration', at: '2026-07-01T00:00:00.000Z', name: 'Первый пользователь', userId: 'qa-user-1' },
    ],
  },
  '/api/admin/mailings/overview': {
    campaigns: [{
      id: 'mailing-qa-1', subject: 'Прошлая рассылка', preheader: 'Архив', templateKey: 'blank', segment: 'active',
      status: 'completed', recipientCount: 3, acceptedCount: 3, failedCount: 0, skippedCount: 0,
      createdAt: '2026-07-10T00:00:00.000Z', startedAt: '2026-07-10T00:01:00.000Z', completedAt: '2026-07-10T00:02:00.000Z', error: '',
    }],
    templates: [{
      id: 'latest-article', label: 'Свежая статья', description: 'Анонс нового материала',
      subject: 'Новая статья Manacost', preheader: 'Читайте свежий материал', htmlBody: '<h2>Новая статья</h2><p>Текст анонса.</p>',
    }],
    contacts: [{
      id: 'mail-contact-1', email: 'reader@example.test', name: 'Читатель', consentStatus: 'subscribed', consentSource: 'profile',
      lifecycle: 'active', accountState: 'current', eligible: true, updatedAt: '2026-07-11T00:00:00.000Z',
    }],
    summary: { total: 4, eligible: 3, active: 2, former: 1, excluded: 1, unsubscribed: 1, pendingConsent: 0, suppressed: 0 },
    transport: { configured: true, from: 'Manacost <news@example.test>' },
  },
  '/api/admin/mailings/preview': {
    html: '<!doctype html><html lang="ru"><body><h1>Предпросмотр QA</h1></body></html>',
    recipientCount: 3,
    sanitizedHtmlBody: '<h1>Предпросмотр QA</h1>',
    previewDigest: 'qa-preview-digest',
  },
  '/api/admin/boosty/analytics': {
    semantics: 'combined_subscription_events',
    from: '2026-07-01T00:00:00.000Z',
    to: '2026-07-29T00:00:00.000Z',
    summary: { newSubscriptions: 2, renewals: 3, revenueRub: 2500, observedDecreaseRub: 0 },
    plans: [],
    retention: [],
    coverage: {
      baselineAt: '2026-07-01T00:00:00.000Z',
      lastAcceptedPollAt: '2026-07-28T00:00:00.000Z',
      acceptedPolls: 28,
      maxPollGapSeconds: 86400,
      complete: true,
    },
    articleIntervals: [],
    generatedAt: '2026-07-28T00:00:00.000Z',
    limitations: [],
    sourceBreakdown: [],
    sales: null,
  },
  '/api/admin/fun-decks': {
    fetchedAt: '2026-07-28T00:00:00.000Z',
    detectorVersion: 'qa-v1',
    stats: { published_by_format: { standard: 0, wild: 0 }, rejected: 0, candidates: 0 },
    cadence: { label: 'Дважды в час', timers: ['15', '45'], schedule: ':15 / :45' },
    decks: [],
  },
  '/api/admin/api-keys': { keys: [] },
  '/api/admin/arena-synergies': {
    schemaVersion: 2,
    generatedAt: '2026-07-28T00:00:00.000Z',
    selectedClass: 'ALL',
    source: { winningDecksFetchedAt: '2026-07-28T00:00:00.000Z', cardStatsFetchedAt: null },
    cohort: {
      id: 'qa-arena-cohort',
      patchVersion: '36.0.3',
      patchPublishedAt: '2026-07-20T00:00:00.000Z',
      poolFingerprint: 'qa-arena-pool-fingerprint',
      from: '2026-07-20T00:00:00.000Z',
      to: '2026-07-28T00:00:00.000Z',
    },
    summary: { runsAvailable: 24, runsAnalyzed: 24, redraftRuns: 5, recordCounts: { '12-0': 8 }, warnings: [] },
    availableClasses: [{ id: 'ALL', label: 'Все классы', runs: 24 }],
    methodology: {
      sampleLimit: 1000,
      minimumPairRuns: 5,
      minimumLift: 1.05,
      packageFilterShare: 0.8,
      classStratified: true,
      outcomeMetric: '12-win run quality',
      note: 'Контрольная детерминированная выборка.',
    },
    dataQuality: { status: 'healthy', score: 100, metrics: {}, checks: [] },
    reliability: {
      sampleMode: 'stable',
      servedFrom: 'live',
      currentWeight: 1,
      historicalWeight: 0,
      stableAtRuns: 20,
      previousCohortId: null,
      limitations: [],
    },
    history: [],
    combinations: [],
    redraft: [],
  },
};

export const wildMatchupsFixture = {
  format: 'wild',
  formatLabel: 'Вольный',
  rank: 'legend',
  rankLabel: 'Легенда',
  source: 'hsguru',
  updatedAt: '2026-07-12T00:00:00.000Z',
  columns: [
    { name: 'Wild Control Rogue', label: 'Вольный Контроль Разбойник', popularity: '14,2%' },
    { name: 'Wild Reno Mage', label: 'Вольный Рено Маг', popularity: '8,1%' },
    { name: 'Wild Pirate Warrior', label: 'Вольный Пират Воин', popularity: '6,7%' },
    { name: 'Other Rogue', label: 'Other Rogue', popularity: '2,4%' },
  ],
  rows: [
    {
      archetype: 'Wild Control Rogue',
      archetypeLabel: 'Вольный Контроль Разбойник',
      winrate: 55.6,
      cells: [
        { opponent: 'Wild Control Rogue', opponentLabel: 'Вольный Контроль Разбойник', winrate: 50 },
        { opponent: 'Wild Reno Mage', opponentLabel: 'Вольный Рено Маг', winrate: 57.2 },
        { opponent: 'Wild Pirate Warrior', opponentLabel: 'Вольный Пират Воин', winrate: 45.4 },
        { opponent: 'Other Rogue', opponentLabel: 'Other Rogue', winrate: 52.1 },
      ],
    },
    {
      archetype: 'Wild Reno Mage',
      archetypeLabel: 'Вольный Рено Маг',
      winrate: 51.8,
      cells: [
        { opponent: 'Wild Control Rogue', opponentLabel: 'Вольный Контроль Разбойник', winrate: 42.8 },
        { opponent: 'Wild Reno Mage', opponentLabel: 'Вольный Рено Маг', winrate: 50 },
        { opponent: 'Wild Pirate Warrior', opponentLabel: 'Вольный Пират Воин', winrate: 53.9 },
        { opponent: 'Other Rogue', opponentLabel: 'Other Rogue', winrate: 48.4 },
      ],
    },
    {
      archetype: 'Wild Pirate Warrior',
      archetypeLabel: 'Вольный Пират Воин',
      winrate: 49.7,
      cells: [
        { opponent: 'Wild Control Rogue', opponentLabel: 'Вольный Контроль Разбойник', winrate: 54.6 },
        { opponent: 'Wild Reno Mage', opponentLabel: 'Вольный Рено Маг', winrate: 46.1 },
        { opponent: 'Wild Pirate Warrior', opponentLabel: 'Вольный Пират Воин', winrate: 50 },
        { opponent: 'Other Rogue', opponentLabel: 'Other Rogue', winrate: 51.3 },
      ],
    },
    {
      archetype: 'Other Rogue',
      archetypeLabel: 'Other Rogue',
      winrate: 49.1,
      cells: [
        { opponent: 'Wild Control Rogue', opponentLabel: 'Вольный Контроль Разбойник', winrate: 47.9 },
        { opponent: 'Wild Reno Mage', opponentLabel: 'Вольный Рено Маг', winrate: 51.6 },
        { opponent: 'Wild Pirate Warrior', opponentLabel: 'Вольный Пират Воин', winrate: 48.7 },
        { opponent: 'Other Rogue', opponentLabel: 'Other Rogue', winrate: 50 },
      ],
    },
  ],
};

export const publicStandardFixtureAliases = {
  '/api/constructed-cards': '/api/admin/constructed-cards',
  '/api/constructed-cards/CARD_QA_1': '/api/admin/constructed-cards/CARD_QA_1',
  '/api/standard-meta': '/api/admin/standard-meta',
  '/api/standard-meta/teaser': '/api/admin/standard-meta',
  '/api/vicious-syndicate-gold': '/api/admin/vicious-syndicate-gold',
  '/api/vicious-syndicate-gold/builds': '/api/admin/vicious-syndicate-gold/builds',
};
