export const battlegroundMinionIconByRussianName: Record<string, string> = {
  Аберрация: '/bg-legacy/assset/aberration.webp',
  Аберрации: '/bg-legacy/assset/aberration.webp',
  Механизмы: '/bg-legacy/assset/механизмы.webp',
  Механизм: '/bg-legacy/assset/механизмы.webp',
  Мурлоки: '/bg-legacy/assset/мурлоки.webp',
  Мурлок: '/bg-legacy/assset/мурлоки.webp',
  Звери: '/bg-legacy/assset/зверь.webp',
  Зверь: '/bg-legacy/assset/зверь.webp',
  Демоны: '/bg-legacy/assset/демоны.webp',
  Демон: '/bg-legacy/assset/демоны.webp',
  Драконы: '/bg-legacy/assset/драконы.webp',
  Дракон: '/bg-legacy/assset/драконы.webp',
  Нежить: '/bg-legacy/assset/нежить.webp',
  Нага: '/bg-legacy/assset/наги.webp',
  Наги: '/bg-legacy/assset/наги.webp',
  Элементали: '/bg-legacy/assset/элементали.webp',
  Элементаль: '/bg-legacy/assset/элементали.webp',
  Пираты: '/bg-legacy/assset/пираты.webp',
  Пират: '/bg-legacy/assset/пираты.webp',
  Свинобраз: '/bg-legacy/assset/свинобразы.webp',
  Свинобразы: '/bg-legacy/assset/свинобразы.webp',
};

export const battlegroundMinionIconBySlug: Record<string, string> = {
  all: '/bg-legacy/assset/общее.webp',
  aberration: '/bg-legacy/assset/aberration.webp',
  mech: '/bg-legacy/assset/механизмы.webp',
  mechanical: '/bg-legacy/assset/механизмы.webp',
  murloc: '/bg-legacy/assset/мурлоки.webp',
  beast: '/bg-legacy/assset/зверь.webp',
  demon: '/bg-legacy/assset/демоны.webp',
  dragon: '/bg-legacy/assset/драконы.webp',
  undead: '/bg-legacy/assset/нежить.webp',
  naga: '/bg-legacy/assset/наги.webp',
  elemental: '/bg-legacy/assset/элементали.webp',
  pirate: '/bg-legacy/assset/пираты.webp',
  quilboar: '/bg-legacy/assset/свинобразы.webp',
};

